version: "3.7"

services:
  api:
    container_name: book-app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://username:password@db:5432/book-app
    volumes:
      - ./app:/app
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=book-app
    ports:
      - 5436:5432

volumes:
  postgres_data:
