version: "3.7"

services:
  db:
    image: postgres:12.0
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=book-app-test
    ports:
      - 5440:5432

volumes:
  postgres_test_data:
